<?php
// /MoralMatrix/ccdu/violations_report_pdf.php
if (session_status() !== PHP_SESSION_ACTIVE) session_start();
require __DIR__ . '/../config.php';

// --- Locate Dompdf (works on both local + live) ---
$autoloadLocal = __DIR__ . '/../vendor/autoload.php';
$autoloadWeb   = $_SERVER['DOCUMENT_ROOT'] . BASE_PATH . '/vendor/autoload.php';
if (file_exists($autoloadLocal)) {
    require_once $autoloadLocal;
} elseif (file_exists($autoloadWeb)) {
    require_once $autoloadWeb;
} else {
    die("❌ Dompdf not found. Please run: composer require dompdf/dompdf");
}

use Dompdf\Dompdf;
use Dompdf\Options;

// --- Capture clean report HTML (without UI header) ---
ob_start();
$skipHeader = true; // this prevents includes/header.php inside the report

$reportPath = realpath(__DIR__ . DIRECTORY_SEPARATOR . 'summary_report.php');
if (!$reportPath || !file_exists($reportPath)) {
    die("❌ Report file not found at: " . htmlspecialchars(__DIR__ . DIRECTORY_SEPARATOR . 'summary_report.php'));
}

include_once $reportPath;
$html = ob_get_clean();

// --- Strip out any leftover <script> tags or UI elements ---
$html = preg_replace('~<script[^>]*>.*?</script>~is', '', $html);

// --- Add MCC Header / Footer ---
$header = '
<div style="display:flex;align-items:center;border-bottom:2px solid #8c1c13;padding-bottom:10px;margin-bottom:20px;">
  <div style="font-family:Arial,Helvetica,sans-serif;">
    <h2 style="margin:0;color:#8c1c13;">Mabalacat City College</h2>
    <p style="margin:2px 0 0;font-size:13px;">Center for Character Development Unit</p>
    <p style="margin:0;font-size:12px;color:#555;">Dolores, Mabalacat City, Pampanga</p>
  </div>
</div>';

$footer = '
<div style="text-align:center;margin-top:20px;font-size:12px;color:#555;border-top:1px solid #ccc;padding-top:6px;">
  Generated by Moral Matrix · ' . date('F d, Y g:i A') . '
</div>';

$html = '<html><body style="font-family:Arial,Helvetica,sans-serif;">' . $header . $html . $footer . '</body></html>';

// --- Generate PDF ---
$options = new Options();
$options->set('isRemoteEnabled', true);
$options->set('isHtml5ParserEnabled', true);
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

// --- Output as downloadable PDF ---
$filename = 'Violation_Summary_Report_' . date('Y-m-d_His') . '.pdf';
$dompdf->stream($filename, ['Attachment' => true]);
exit;
?>
